import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'
import ProductCard from '../components/common/ProductCard'
import Navbar from '../components/common/Navbar'
import BannerCarousel from '../components/common/BannerCarousel'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Navbar/>
        <BannerCarousel/>
        <h1>Best Seller</h1>
        <div className='productItemContainer'>
          <ProductCard/>
        </div>
      </main>
    </>
  )
}
